# Generated by Django 3.0.2 on 2020-05-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
